blank_issues_enabled: false
contact_links:
  - name: How to contribute or where to ask questions
    url: https://git.dec05eba.com/?p=about
    about: Information about how to contribute or where to ask questions
